/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Myself\\documents\\rookienotes\\packages\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-4eff235a",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4eff235a").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-f748169c",
    path: "/faq/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f748169c").then(next)
    },
  },
  {
    path: "/faq/index.html",
    redirect: "/faq/"
  },
  {
    name: "v-45d6ee94",
    path: "/config/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-45d6ee94").then(next)
    },
  },
  {
    path: "/config/index.html",
    redirect: "/config/"
  },
  {
    name: "v-3472a6bb",
    path: "/api/cli.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3472a6bb").then(next)
    },
  },
  {
    name: "v-067128ce",
    path: "/api/node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-067128ce").then(next)
    },
  },
  {
    name: "v-ecbb4534",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ecbb4534").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-0c822f5b",
    path: "/guide/assets.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c822f5b").then(next)
    },
  },
  {
    name: "v-6694535f",
    path: "/guide/basic-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6694535f").then(next)
    },
  },
  {
    name: "v-28f9f993",
    path: "/guide/deploy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-28f9f993").then(next)
    },
  },
  {
    name: "v-70e6001b",
    path: "/guide/directory-structure.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-70e6001b").then(next)
    },
  },
  {
    name: "v-79bf1c8a",
    path: "/guide/frontmatter.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-79bf1c8a").then(next)
    },
  },
  {
    name: "v-4949b50a",
    path: "/guide/getting-started.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4949b50a").then(next)
    },
  },
  {
    name: "v-e9745cb6",
    path: "/guide/i18n.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e9745cb6").then(next)
    },
  },
  {
    name: "v-8fa6b6ca",
    path: "/guide/global-computed.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8fa6b6ca").then(next)
    },
  },
  {
    name: "v-03f03c8a",
    path: "/guide/markdown-slot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-03f03c8a").then(next)
    },
  },
  {
    name: "v-e41467fa",
    path: "/guide/markdown.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e41467fa").then(next)
    },
  },
  {
    name: "v-5b531e51",
    path: "/guide/permalinks.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5b531e51").then(next)
    },
  },
  {
    name: "v-7bb0d29b",
    path: "/miscellaneous/local-development.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7bb0d29b").then(next)
    },
  },
  {
    name: "v-0979f4db",
    path: "/guide/using-vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0979f4db").then(next)
    },
  },
  {
    name: "v-0d300eee",
    path: "/miscellaneous/glossary.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d300eee").then(next)
    },
  },
  {
    name: "v-79d3f2fb",
    path: "/miscellaneous/design-concepts.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-79d3f2fb").then(next)
    },
  },
  {
    name: "v-611966d4",
    path: "/plugin/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-611966d4").then(next)
    },
  },
  {
    path: "/plugin/index.html",
    redirect: "/plugin/"
  },
  {
    name: "v-6c31e37e",
    path: "/plugin/context-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6c31e37e").then(next)
    },
  },
  {
    name: "v-a926baca",
    path: "/miscellaneous/migration-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a926baca").then(next)
    },
  },
  {
    name: "v-6e26c996",
    path: "/plugin/life-cycle.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e26c996").then(next)
    },
  },
  {
    name: "v-005e2550",
    path: "/plugin/official/plugin-active-header-links.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-005e2550").then(next)
    },
  },
  {
    name: "v-278a5fc6",
    path: "/plugin/official/plugin-back-to-top.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-278a5fc6").then(next)
    },
  },
  {
    name: "v-327061f0",
    path: "/plugin/official/plugin-google-analytics.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-327061f0").then(next)
    },
  },
  {
    name: "v-73837348",
    path: "/plugin/official/plugin-last-updated.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-73837348").then(next)
    },
  },
  {
    name: "v-6b1f9ac2",
    path: "/plugin/official/plugin-medium-zoom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6b1f9ac2").then(next)
    },
  },
  {
    name: "v-5b027abc",
    path: "/plugin/official/plugin-nprogress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5b027abc").then(next)
    },
  },
  {
    name: "v-2fdd86b8",
    path: "/plugin/official/plugin-pwa.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2fdd86b8").then(next)
    },
  },
  {
    name: "v-2dc88418",
    path: "/plugin/official/plugin-register-components.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2dc88418").then(next)
    },
  },
  {
    name: "v-05582648",
    path: "/plugin/official/plugin-search.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-05582648").then(next)
    },
  },
  {
    name: "v-d5924f56",
    path: "/plugin/using-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d5924f56").then(next)
    },
  },
  {
    name: "v-9256edd6",
    path: "/plugin/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9256edd6").then(next)
    },
  },
  {
    name: "v-6c94950c",
    path: "/theme/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6c94950c").then(next)
    },
  },
  {
    path: "/theme/index.html",
    redirect: "/theme/"
  },
  {
    name: "v-0654f656",
    path: "/plugin/writing-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0654f656").then(next)
    },
  },
  {
    name: "v-3d03aed2",
    path: "/theme/default-theme-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3d03aed2").then(next)
    },
  },
  {
    name: "v-4370df9b",
    path: "/theme/inheritance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4370df9b").then(next)
    },
  },
  {
    name: "v-62161537",
    path: "/theme/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-62161537").then(next)
    },
  },
  {
    name: "v-e6ff994a",
    path: "/theme/using-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e6ff994a").then(next)
    },
  },
  {
    name: "v-16a5c34a",
    path: "/theme/writing-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-16a5c34a").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]